give @s ocrp:cooked_vension
give @s ocrp:boquette
give @s ocrp:cooked_chicken_nugget
give @s ocrp:piece_of_cake
give @s ocrp:roasted_ribs
give @s ocrp:raw_vension
give @s ocrp:raw_ribs
give @s ocrp:raw_chicken_nugget
give @s ocrp:honey_soup
give @s ocrp:plate
give @s ocrp:chocolate_ice_cream_cup
give @s ocrp:ice_cream_cup
give @s ocrp:honey_ice_cream_cup
give @s ocrp:mixed_fruit_ice_cream_cup
give @s ocrp:croissant
give @s ocrp:cup
give @s ocrp:sunflower_cookie
give @s ocrp:melon_pan
give @s ocrp:sunflower_seeds
give @s ocrp:berries_ice_cream_cup
give @s ocrp:glow_berries_pie
give @s ocrp:sunflower_bread
give @s ocrp:roasted_sunflower_seeds
give @s ocrp:sunflower_biscuit
give @s ocrp:toasted_seeds
give @s ocrp:glow_berries_salad
give @s ocrp:tropical_salad
give @s ocrp:gozinaki
give @s ocrp:chicken_nuggets_cup_half
give @s ocrp:toasted_pumpkin_seeds
give @s ocrp:chicken_nuggets_cup_f
give @s ocrp:french_fries
give @s ocrp:cod_soup
give @s ocrp:steak_dish
give @s ocrp:vension_dish
give @s ocrp:heavy_dish
give @s ocrp:potato_steak_dish
give @s ocrp:pork_dish
give @s ocrp:potato_camel_dish
give @s ocrp:chicken_dish
give @s ocrp:llama_dish
give @s ocrp:rib_sandwich
give @s ocrp:potato_rib_dish
give @s ocrp:potato_chicken_dish
give @s ocrp:wheat_cone
give @s ocrp:cooked_cone
give @s ocrp:ice_cream
give @s ocrp:honey_ice_cream
give @s ocrp:chocolate_ice_cream
give @s ocrp:horse_meat
give @s ocrp:cooked_horse_meat
give @s ocrp:raw_polar_bear_meat
give @s ocrp:cherry_ice_cream
give @s ocrp:cooked_polar_bear_meat
give @s ocrp:raw_camel_meat
give @s ocrp:chocolate
give @s ocrp:cooked_camel_meat
give @s ocrp:roasted_cocoa
give @s ocrp:frogs_legs
give @s ocrp:cooked_frog_legs
give @s ocrp:sweet_berry_bottle
give @s ocrp:chocolate_cookie
give @s ocrp:chocolate_bread
give @s ocrp:honey_sweet_berries
give @s ocrp:chocolate_pie
give @s ocrp:sweet_berry_pie
give @s ocrp:bowl_of_salad
give @s ocrp:cooked_carrot
give @s ocrp:cooked_beetroot
give @s ocrp:beef_burger
give @s ocrp:burger_bun
give @s ocrp:pita_bread
give @s ocrp:corp_salad
give @s ocrp:burger_pork_chop
give @s ocrp:pumpkin_slice
give @s ocrp:pumpkin_soup
give @s ocrp:steak_stew
give @s ocrp:chicken_stew
give @s ocrp:mashed_potato
give @s ocrp:shawarma
give @s ocrp:fried_egg
give @s ocrp:cooked_squid_tentacle
give @s ocrp:squid_tentacle
give @s ocrp:cooked_llama
give @s ocrp:raw_llama
give @s ocrp:turtle_fried_egg
give @s ocrp:bat_wings
give @s ocrp:bat_stew
give @s ocrp:raw_donut
give @s ocrp:chocolate_bucket_full
give @s ocrp:bucket_chocolate_low
give @s ocrp:honey_apple
give @s ocrp:plain_donut
give @s ocrp:honey_bread
give @s ocrp:chocolate_bucket_mid
give @s ocrp:carrot_stew
give @s ocrp:sweet_berries_donut
give @s ocrp:honey_donut
give @s ocrp:apple_donut
give @s ocrp:chocolate_donut
give @s ocrp:pumpkin_donut
give @s ocrp:fruit_bowl
give @s ocrp:cactus_chunk
give @s ocrp:llama_shawarma
give @s ocrp:tortila
give @s ocrp:beef_taco
give @s ocrp:beef_burger_egg
give @s ocrp:egg_burger_porkchop
give @s ocrp:porkchop_turtle_burger
give @s ocrp:cactus_soup
give @s ocrp:turtle_beef_burger
give @s ocrp:horse_meat_burger
give @s ocrp:egg_horse_burger
give @s ocrp:chicken_taco
give @s ocrp:horse_turtle_burger
give @s ocrp:cooked_beef_skewer_l
give @s ocrp:raw_beef_skewer
give @s ocrp:skewer_stick
give @s ocrp:cooked_beef_skewer_m
give @s ocrp:raw_pork_skewer
give @s ocrp:cooked_pork_skewer_l
give @s ocrp:cooked_beef_skewer
give @s ocrp:cooked_salmon_skewer_f
give @s ocrp:raw_tentacle_skewer
give @s ocrp:raw_salmon_skewer
give @s ocrp:cooked_salmon_skewer_l
give @s ocrp:cooked_salmon_skewer_m
give @s ocrp:cooked_pork_skewer_f
give @s ocrp:cooked_tentacle_skewer_l
give @s ocrp:cooked_pork_skewer
give @s ocrp:cooked_tentacle_skewer_f
give @s ocrp:raw_bear_skewer
give @s ocrp:cooked_camel_skewer_l
give @s ocrp:cooked_tentacle_skewer_m
give @s ocrp:cooked_bear_skewer_f
give @s ocrp:cooked_bear_skewer_m
give @s ocrp:cooked_bea_skewer_l
give @s ocrp:raw_camel_skewer
give @s ocrp:cooked_camel_skewer_m
give @s ocrp:cooked_camel_skewer_f
give @s ocrp:cooked_cod_skewer_l
give @s ocrp:cooked_skewer_cod_f
give @s ocrp:raw_cod_skewer
give @s ocrp:cooked_skewer_cod_m
