give @s ber:cooked_vension
give @s ber:boquette
give @s ber:cooked_chicken_nugget
give @s ber:piece_of_cake
give @s ber:roasted_ribs
give @s ber:raw_vension
give @s ber:raw_ribs
give @s ber:raw_chicken_nugget
give @s ber:honey_soup
give @s ber:plate
give @s ber:chocolate_ice_cream_cup
give @s ber:ice_cream_cup
give @s ber:honey_ice_cream_cup
give @s ber:mixed_fruit_ice_cream_cup
give @s ber:croissant
give @s ber:cup
give @s ber:sunflower_cookie
give @s ber:melon_pan
give @s ber:sunflower_seeds
give @s ber:berries_ice_cream_cup
give @s ber:glow_berries_pie
give @s ber:sunflower_bread
give @s ber:roasted_sunflower_seeds
give @s ber:sunflower_biscuit
give @s ber:toasted_seeds
give @s ber:glow_berries_salad
give @s ber:tropical_salad
give @s ber:gozinaki
give @s ber:chicken_nuggets_cup_half
give @s ber:toasted_pumpkin_seeds
give @s ber:chicken_nuggets_cup_f
give @s ber:french_fries
give @s ber:cod_soup
give @s ber:steak_dish
give @s ber:vension_dish
give @s ber:heavy_dish
give @s ber:potato_steak_dish
give @s ber:pork_dish
give @s ber:potato_camel_dish
give @s ber:chicken_dish
give @s ber:llama_dish
give @s ber:rib_sandwich
give @s ber:potato_rib_dish
give @s ber:potato_chicken_dish
give @s ber:wheat_cone
give @s ber:cooked_cone
give @s ber:ice_cream
give @s ber:honey_ice_cream
give @s ber:chocolate_ice_cream
give @s ber:horse_meat
give @s ber:cooked_horse_meat
give @s ber:raw_polar_bear_meat
give @s ber:cherry_ice_cream
give @s ber:cooked_polar_bear_meat
give @s ber:raw_camel_meat
give @s ber:chocolate
give @s ber:cooked_camel_meat
give @s ber:roasted_cocoa
give @s ber:frogs_legs
give @s ber:cooked_frog_legs
give @s ber:sweet_berry_bottle
give @s ber:chocolate_cookie
give @s ber:chocolate_bread
give @s ber:honey_sweet_berries
give @s ber:chocolate_pie
give @s ber:sweet_berry_pie
give @s ber:bowl_of_salad
give @s ber:cooked_carrot
give @s ber:cooked_beetroot
give @s ber:beef_burger
give @s ber:burger_bun
give @s ber:pita_bread
give @s ber:corp_salad
give @s ber:burger_pork_chop
give @s ber:pumpkin_slice
give @s ber:pumpkin_soup
give @s ber:steak_stew
give @s ber:chicken_stew
give @s ber:mashed_potato
give @s ber:shawarma
give @s ber:fried_egg
give @s ber:cooked_squid_tentacle
give @s ber:squid_tentacle
give @s ber:cooked_llama
give @s ber:raw_llama
give @s ber:turtle_fried_egg
give @s ber:bat_wings
give @s ber:bat_stew
give @s ber:raw_donut
give @s ber:chocolate_bucket_full
give @s ber:bucket_chocolate_low
give @s ber:honey_apple
give @s ber:plain_donut
give @s ber:honey_bread
give @s be:chocolate_bucket_mid
give @s ber:carrot_stew
give @s ber:sweet_berries_donut
give @s ber:honey_donut
give @s ber:apple_donut
give @s ber:chocolate_donut
give @s ber:pumpkin_donut
give @s ber:fruit_bowl
give @s ber:cactus_chunk
give @s ber:llama_shawarma
give @s ber:tortila
give @s ber:beef_taco
give @s ber:beef_burger_egg
give @s ber:egg_burger_porkchop
give @s ber:porkchop_turtle_burger
give @s ber:cactus_soup
give @s ber:turtle_beef_burger
give @s ber:horse_meat_burger
give @s ber:egg_horse_burger
give @s ber:chicken_taco
give @s ber:horse_turtle_burger
give @s ber:cooked_beef_skewer_l
give @s ber:raw_beef_skewer
give @s ber:skewer_stick
give @s ber:cooked_beef_skewer_m
give @s ber:raw_pork_skewer
give @s ber:cooked_pork_skewer_l
give @s ber:cooked_beef_skewer
give @s ber:cooked_salmon_skewer_f
give @s ber:raw_tentacle_skewer
give @s ber:raw_salmon_skewer
give @s ber:cooked_salmon_skewer_l
give @s ber:cooked_salmon_skewer_m
give @s ber:cooked_pork_skewer_f
give @s ber:cooked_tentacle_skewer_l
give @s ber:cooked_pork_skewer
give @s ber:cooked_tentacle_skewer_f
give @s ber:raw_bear_skewer
give @s ber:cooked_camel_skewer_l
give @s ber:cooked_tentacle_skewer_m
give @s ber:cooked_bear_skewer_f
give @s ber:cooked_bear_skewer_m
give @s ber:cooked_bea_skewer_l
give @s ber:raw_camel_skewer
give @s ber:cooked_camel_skewer_m
give @s ber:cooked_camel_skewer_f
give @s ber:cooked_cod_skewer_l
give @s ber:cooked_skewer_cod_f
give @s ber:raw_cod_skewer
give @s ber:cooked_skewer_cod_m
