execute as @s if block ~~-1~ log [] run fill ~~-1~~~~ air [] destroy
execute as @s if block ~~-1~ log2 [] run fill ~~-1~~~~ air [] destroy
execute as @s if block ~~-1~ crimson_stem [] run fill ~~-1~~~~ air [] destroy
execute as @s if block ~~-1~ warped_stem [] run fill ~~-1~~~~ air [] destroy
execute as @s if block ~~-2~ log [] run fill ~~-2~~~~ air [] destroy
execute as @s if block ~~-2~ log2 [] run fill ~~-2~~~~ air [] destroy
execute as @s if block ~~-2~ crimson_stem [] run fill ~~-2~~~~ air [] destroy
execute as @s if block ~~-2~ warped_stem [] run fill ~~-2~~~~ air [] destroy
execute as @s if block ~~-3~ log [] run fill ~~-3~~~~ air [] destroy
execute as @s if block ~~-3~ log2 [] run fill ~~-3~~~~ air [] destroy
execute as @s if block ~~-3~ crimson_stem [] run fill ~~-3~~~~ air [] destroy
execute as @s if block ~~-3~ warped_stem [] run fill ~~-3~~~~ air [] destroy
execute as @s if block ~~-4~ log [] run fill ~~-4~~~~ air [] destroy
execute as @s if block ~~-4~ log2 [] run fill ~~-4~~~~ air [] destroy
execute as @s if block ~~-4~ crimson_stem [] run fill ~~-4~~~~ air [] destroy
execute as @s if block ~~-4~ warped_stem [] run fill ~~-4~~~~ air [] destroy
execute as @s if block ~~-5~ log [] run fill ~~-5~~~~ air [] destroy
execute as @s if block ~~-5~ log2 [] run fill ~~-5~~~~ air [] destroy
execute as @s if block ~~-5~ crimson_stem [] run fill ~~-5~~~~ air [] destroy
execute as @s if block ~~-5~ warped_stem [] run fill ~~-5~~~~ air [] destroy
execute as @s if block ~~-6~ log [] run fill ~~-6~~~~ air [] destroy
execute as @s if block ~~-6~ log2 [] run fill ~~-6~~~~ air [] destroy
execute as @s if block ~~-6~ crimson_stem [] run fill ~~-6~~~~ air [] destroy
execute as @s if block ~~-6~ warped_stem [] run fill ~~-6~~~~ air [] destroy
execute as @s if block ~~-7~ log [] run fill ~~-7~~~~ air [] destroy
execute as @s if block ~~-7~ log2 [] run fill ~~-7~~~~ air [] destroy
execute as @s if block ~~-7~ crimson_stem [] run fill ~~-7~~~~ air [] destroy
execute as @s if block ~~-7~ warped_stem [] run fill ~~-7~~~~ air [] destroy
execute as @s if block ~~-8~ log [] run fill ~~-8~~~~ air [] destroy
execute as @s if block ~~-8~ log2 [] run fill ~~-8~~~~ air [] destroy
execute as @s if block ~~-8~ crimson_stem [] run fill ~~-8~~~~ air [] destroy
execute as @s if block ~~-8~ warped_stem [] run fill ~~-8~~~~ air [] destroy
execute as @s if block ~~-9~ log [] run fill ~~-9~~~~ air [] destroy
execute as @s if block ~~-9~ log2 [] run fill ~~-9~~~~ air [] destroy
execute as @s if block ~~-9~ crimson_stem [] run fill ~~-9~~~~ air [] destroy
execute as @s if block ~~-9~ warped_stem [] run fill ~~-9~~~~ air [] destroy
execute as @s if block ~~-10~ log [] run fill ~~-10~~~~ air [] destroy
execute as @s if block ~~-10~ log2 [] run fill ~~-10~~~~ air [] destroy
execute as @s if block ~~-10~ crimson_stem [] run fill ~~-10~~~~ air [] destroy
execute as @s if block ~~-10~ warped_stem [] run fill ~~-10~~~~ air [] destroy




execute as @s if block ~1~~ log [] run fill ~1~~~~~ air [] destroy
execute as @s if block ~-1~~ log [] run fill ~-1~~~~~ air [] destroy
execute as @s if block ~~~1 log [] run fill ~~~1~~~ air [] destroy
execute as @s if block ~~~-1 log [] run fill ~~~-1~~~ air [] destroy

execute as @s if block ~1~~ log [] run fill ~1~~~~~ air [] destroy
execute as @s if block ~-1~~ log [] run fill ~-1~~~~~ air [] destroy
execute as @s if block ~~~1 log [] run fill ~~~1~~~ air [] destroy
execute as @s if block ~~~-1 log [] run fill ~~~-1~~~ air [] destroy

execute as @s if block ~1~~ log [] run fill ~1~~~~~ air [] destroy
execute as @s if block ~-1~~ log [] run fill ~-1~~~~~ air [] destroy
execute as @s if block ~~~1 log [] run fill ~~~1~~~ air [] destroy
execute as @s if block ~~~-1 log [] run fill ~~~-1~~~ air [] destroy

execute as @s if block ~1~~ log [] run fill ~1~~~~~ air [] destroy
execute as @s if block ~-1~~ log [] run fill ~-1~~~~~ air [] destroy
execute as @s if block ~~~1 log [] run fill ~~~1~~~ air [] destroy
execute as @s if block ~~~-1 log [] run fill ~~~-1~~~ air [] destroy

execute as @s if block ~1~~ log2 [] run fill ~1~~~~~ air [] destroy
execute as @s if block ~-1~~ log2 [] run fill ~-1~~~~~ air [] destroy
execute as @s if block ~~~1 log2 [] run fill ~~~1~~~ air [] destroy
execute as @s if block ~~~-1 log2 [] run fill ~~~-1~~~ air [] destroy

execute as @s if block ~1~~ log [] run fill ~1~~~~~ air [] destroy
execute as @s if block ~-1~~ log [] run fill ~-1~~~~~ air [] destroy
execute as @s if block ~~~1 log [] run fill ~~~1~~~ air [] destroy
execute as @s if block ~~~-1 log [] run fill ~~~-1~~~ air [] destroy

execute as @s if block ~1~~ warped_stem [] run fill ~1~~~~~ air [] destroy
execute as @s if block ~-1~~ warped_stem [] run fill ~-1~~~~~ air [] destroy
execute as @s if block ~~~1 warped_stem [] run fill ~~~1~~~ air [] destroy
execute as @s if block ~~~-1 warped_stem [] run fill ~~~-1~~~ air [] destroy

execute as @s if block ~1~~ crimson_stem [] run fill ~1~~~~~ air [] destroy
execute as @s if block ~-1~~ crimson_stem [] run fill ~-1~~~~~ air [] destroy
execute as @s if block ~~~1 crimson_stem [] run fill ~~~1~~~ air [] destroy
execute as @s if block ~~~-1 crimson_stem [] run fill ~~~-1~~~ air [] destroy

execute as @s if block ~~1~ log [] run fill ~~1~~~~ air [] destroy
execute as @s if block ~~2~ log [] run fill ~~2~~~~ air [] destroy
execute as @s if block ~~3~ log [] run fill ~~3~~~~ air [] destroy
execute as @s if block ~~4~ log [] run fill ~~4~~~~ air [] destroy
execute as @s if block ~~5~ log [] run fill ~~5~~~~ air [] destroy
execute as @s if block ~~6~ log [] run fill ~~6~~~~ air [] destroy
execute as @s if block ~~7~ log [] run fill ~~7~~~~ air [] destroy
execute as @s if block ~~8~ log [] run fill ~~8~~~~ air [] destroy
execute as @s if block ~~9~ log [] run fill ~~9~~~~ air [] destroy
execute as @s if block ~~10~ log [] run fill ~~10~~~~ air [] destroy
execute as @s if block ~~11~ log [] run fill ~~11~~~~ air [] destroy
execute as @s if block ~~12~ log [] run fill ~~12~~~~ air [] destroy
execute as @s if block ~~13~ log [] run fill ~~13~~~~ air [] destroy
execute as @s if block ~~14~ log [] run fill ~~14~~~~ air [] destroy
execute as @s if block ~~15~ log [] run fill ~~15~~~~ air [] destroy
execute as @s if block ~~16~ log [] run fill ~~16~~~~ air [] destroy
execute as @s if block ~~17~ log [] run fill ~~17~~~~ air [] destroy
execute as @s if block ~~18~ log [] run fill ~~18~~~~ air [] destroy
execute as @s if block ~~19~ log [] run fill ~~19~~~~ air [] destroy
execute as @s if block ~~20~ log [] run fill ~~20~~~~ air [] destroy
execute as @s if block ~~21~ log [] run fill ~~21~~~~ air [] destroy
execute as @s if block ~~22~ log [] run fill ~~22~~~~ air [] destroy
execute as @s if block ~~23~ log [] run fill ~~23~~~~ air [] destroy
execute as @s if block ~~24~ log [] run fill ~~24~~~~ air [] destroy
execute as @s if block ~~25~ log [] run fill ~~25~~~~ air [] destroy
execute as @s if block ~~26~ log [] run fill ~~26~~~~ air [] destroy

execute as @s if block ~~1~ warped_stem [] run fill ~~1~~~~ air [] destroy
execute as @s if block ~~2~ warped_stem [] run fill ~~2~~~~ air [] destroy
execute as @s if block ~~3~ warped_stem [] run fill ~~3~~~~ air [] destroy
execute as @s if block ~~4~ warped_stem [] run fill ~~4~~~~ air [] destroy
execute as @s if block ~~5~ warped_stem [] run fill ~~5~~~~ air [] destroy
execute as @s if block ~~6~ warped_stem [] run fill ~~6~~~~ air [] destroy
execute as @s if block ~~7~ warped_stem [] run fill ~~7~~~~ air [] destroy
execute as @s if block ~~8~ warped_stem [] run fill ~~8~~~~ air [] destroy
execute as @s if block ~~9~ warped_stem [] run fill ~~9~~~~ air [] destroy
execute as @s if block ~~10~ warped_stem [] run fill ~~10~~~~ air [] destroy
execute as @s if block ~~11~ warped_stem [] run fill ~~11~~~~ air [] destroy
execute as @s if block ~~12~ warped_stem [] run fill ~~12~~~~ air [] destroy
execute as @s if block ~~13~ warped_stem [] run fill ~~13~~~~ air [] destroy
execute as @s if block ~~14~ warped_stem [] run fill ~~14~~~~ air [] destroy
execute as @s if block ~~15~ warped_stem [] run fill ~~15~~~~ air [] destroy
execute as @s if block ~~16~ warped_stem [] run fill ~~16~~~~ air [] destroy
execute as @s if block ~~17~ warped_stem [] run fill ~~17~~~~ air [] destroy
execute as @s if block ~~18~ warped_stem [] run fill ~~18~~~~ air [] destroy
execute as @s if block ~~19~ warped_stem [] run fill ~~19~~~~ air [] destroy
execute as @s if block ~~20~ warped_stem [] run fill ~~20~~~~ air [] destroy
execute as @s if block ~~21~ warped_stem [] run fill ~~21~~~~ air [] destroy
execute as @s if block ~~22~ warped_stem [] run fill ~~22~~~~ air [] destroy
execute as @s if block ~~23~ warped_stem [] run fill ~~23~~~~ air [] destroy
execute as @s if block ~~24~ warped_stem [] run fill ~~24~~~~ air [] destroy
execute as @s if block ~~25~ warped_stem [] run fill ~~25~~~~ air [] destroy
execute as @s if block ~~26~ warped_stem [] run fill ~~26~~~~ air [] destroy

execute as @s if block ~~1~ crimson_stem [] run fill ~~1~~~~ air [] destroy
execute as @s if block ~~2~ crimson_stem [] run fill ~~2~~~~ air [] destroy
execute as @s if block ~~3~ crimson_stem [] run fill ~~3~~~~ air [] destroy
execute as @s if block ~~4~ crimson_stem [] run fill ~~4~~~~ air [] destroy
execute as @s if block ~~5~ crimson_stem [] run fill ~~5~~~~ air [] destroy
execute as @s if block ~~6~ crimson_stem [] run fill ~~6~~~~ air [] destroy
execute as @s if block ~~7~ crimson_stem [] run fill ~~7~~~~ air [] destroy
execute as @s if block ~~8~ crimson_stem [] run fill ~~8~~~~ air [] destroy
execute as @s if block ~~9~ crimson_stem [] run fill ~~9~~~~ air [] destroy
execute as @s if block ~~10~ crimson_stem [] run fill ~~10~~~~ air [] destroy
execute as @s if block ~~11~ crimson_stem [] run fill ~~11~~~~ air [] destroy
execute as @s if block ~~12~ crimson_stem [] run fill ~~12~~~~ air [] destroy
execute as @s if block ~~13~ crimson_stem [] run fill ~~13~~~~ air [] destroy
execute as @s if block ~~14~ crimson_stem [] run fill ~~14~~~~ air [] destroy
execute as @s if block ~~15~ crimson_stem [] run fill ~~15~~~~ air [] destroy
execute as @s if block ~~16~ crimson_stem [] run fill ~~16~~~~ air [] destroy
execute as @s if block ~~17~ crimson_stem [] run fill ~~17~~~~ air [] destroy
execute as @s if block ~~18~ crimson_stem [] run fill ~~18~~~~ air [] destroy
execute as @s if block ~~19~ crimson_stem [] run fill ~~19~~~~ air [] destroy
execute as @s if block ~~20~ crimson_stem [] run fill ~~20~~~~ air [] destroy
execute as @s if block ~~21~ crimson_stem [] run fill ~~21~~~~ air [] destroy
execute as @s if block ~~22~ crimson_stem [] run fill ~~22~~~~ air [] destroy
execute as @s if block ~~23~ crimson_stem [] run fill ~~23~~~~ air [] destroy
execute as @s if block ~~24~ crimson_stem [] run fill ~~24~~~~ air [] destroy
execute as @s if block ~~25~ crimson_stem [] run fill ~~25~~~~ air [] destroy
execute as @s if block ~~26~ crimson_stem [] run fill ~~26~~~~ air [] destroy

execute as @s if block ~~1~ log [] run fill ~~1~~~~ air [] destroy
execute as @s if block ~~2~ log [] run fill ~~2~~~~ air [] destroy
execute as @s if block ~~3~ log [] run fill ~~3~~~~ air [] destroy
execute as @s if block ~~4~ log [] run fill ~~4~~~~ air [] destroy
execute as @s if block ~~5~ log [] run fill ~~5~~~~ air [] destroy
execute as @s if block ~~6~ log [] run fill ~~6~~~~ air [] destroy
execute as @s if block ~~7~ log [] run fill ~~7~~~~ air [] destroy
execute as @s if block ~~8~ log [] run fill ~~8~~~~ air [] destroy
execute as @s if block ~~9~ log [] run fill ~~9~~~~ air [] destroy
execute as @s if block ~~10~ log [] run fill ~~10~~~~ air [] destroy
execute as @s if block ~~11~ log [] run fill ~~11~~~~ air [] destroy
execute as @s if block ~~12~ log [] run fill ~~12~~~~ air [] destroy
execute as @s if block ~~13~ log [] run fill ~~13~~~~ air [] destroy
execute as @s if block ~~14~ log [] run fill ~~14~~~~ air [] destroy
execute as @s if block ~~15~ log [] run fill ~~15~~~~ air [] destroy
execute as @s if block ~~16~ log [] run fill ~~16~~~~ air [] destroy
execute as @s if block ~~17~ log [] run fill ~~17~~~~ air [] destroy
execute as @s if block ~~18~ log [] run fill ~~18~~~~ air [] destroy
execute as @s if block ~~19~ log [] run fill ~~19~~~~ air [] destroy
execute as @s if block ~~20~ log [] run fill ~~20~~~~ air [] destroy
execute as @s if block ~~21~ log [] run fill ~~21~~~~ air [] destroy
execute as @s if block ~~22~ log [] run fill ~~22~~~~ air [] destroy
execute as @s if block ~~23~ log [] run fill ~~23~~~~ air [] destroy
execute as @s if block ~~24~ log [] run fill ~~24~~~~ air [] destroy
execute as @s if block ~~25~ log [] run fill ~~25~~~~ air [] destroy
execute as @s if block ~~26~ log [] run fill ~~26~~~~ air [] destroy

execute as @s if block ~~1~ log2 [] run fill ~~1~~~~ air [] destroy
execute as @s if block ~~2~ log2 [] run fill ~~2~~~~ air [] destroy
execute as @s if block ~~3~ log2 [] run fill ~~3~~~~ air [] destroy
execute as @s if block ~~4~ log2 [] run fill ~~4~~~~ air [] destroy
execute as @s if block ~~5~ log2 [] run fill ~~5~~~~ air [] destroy
execute as @s if block ~~6~ log2 [] run fill ~~6~~~~ air [] destroy
execute as @s if block ~~7~ log2 [] run fill ~~7~~~~ air [] destroy
execute as @s if block ~~8~ log2 [] run fill ~~8~~~~ air [] destroy
execute as @s if block ~~9~ log2 [] run fill ~~9~~~~ air [] destroy
execute as @s if block ~~10~ log2 [] run fill ~~10~~~~ air [] destroy
execute as @s if block ~~11~ log2 [] run fill ~~11~~~~ air [] destroy
execute as @s if block ~~12~ log2 [] run fill ~~12~~~~ air [] destroy
execute as @s if block ~~13~ log2 [] run fill ~~13~~~~ air [] destroy
execute as @s if block ~~14~ log2 [] run fill ~~14~~~~ air [] destroy
execute as @s if block ~~15~ log2 [] run fill ~~15~~~~ air [] destroy
execute as @s if block ~~16~ log2 [] run fill ~~16~~~~ air [] destroy
execute as @s if block ~~17~ log2 [] run fill ~~17~~~~ air [] destroy
execute as @s if block ~~18~ log2 [] run fill ~~18~~~~ air [] destroy
execute as @s if block ~~19~ log2 [] run fill ~~19~~~~ air [] destroy
execute as @s if block ~~20~ log2 [] run fill ~~20~~~~ air [] destroy
execute as @s if block ~~21~ log2 [] run fill ~~21~~~~ air [] destroy
execute as @s if block ~~22~ log2 [] run fill ~~22~~~~ air [] destroy
execute as @s if block ~~23~ log2 [] run fill ~~23~~~~ air [] destroy
execute as @s if block ~~24~ log2 [] run fill ~~24~~~~ air [] destroy
execute as @s if block ~~25~ log2 [] run fill ~~25~~~~ air [] destroy
execute as @s if block ~~26~ log2 [] run fill ~~26~~~~ air [] destroy

execute as @s if block ~~1~ log2 [] run fill ~~1~~~~ air [] destroy
execute as @s if block ~~2~ log2 [] run fill ~~2~~~~ air [] destroy
execute as @s if block ~~3~ log2 [] run fill ~~3~~~~ air [] destroy
execute as @s if block ~~4~ log2 [] run fill ~~4~~~~ air [] destroy
execute as @s if block ~~5~ log2 [] run fill ~~5~~~~ air [] destroy
execute as @s if block ~~6~ log2 [] run fill ~~6~~~~ air [] destroy
execute as @s if block ~~7~ log2 [] run fill ~~7~~~~ air [] destroy
execute as @s if block ~~8~ log2 [] run fill ~~8~~~~ air [] destroy
execute as @s if block ~~9~ log2 [] run fill ~~9~~~~ air [] destroy
execute as @s if block ~~10~ log2 [] run fill ~~10~~~~ air [] destroy
execute as @s if block ~~11~ log2 [] run fill ~~11~~~~ air [] destroy
execute as @s if block ~~12~ log2 [] run fill ~~12~~~~ air [] destroy
execute as @s if block ~~13~ log2 [] run fill ~~13~~~~ air [] destroy
execute as @s if block ~~14~ log2 [] run fill ~~14~~~~ air [] destroy
execute as @s if block ~~15~ log2 [] run fill ~~15~~~~ air [] destroy
execute as @s if block ~~16~ log2 [] run fill ~~16~~~~ air [] destroy
execute as @s if block ~~17~ log2 [] run fill ~~17~~~~ air [] destroy
execute as @s if block ~~18~ log2 [] run fill ~~18~~~~ air [] destroy
execute as @s if block ~~19~ log2 [] run fill ~~19~~~~ air [] destroy
execute as @s if block ~~20~ log2 [] run fill ~~20~~~~ air [] destroy
execute as @s if block ~~21~ log2 [] run fill ~~21~~~~ air [] destroy
execute as @s if block ~~22~ log2 [] run fill ~~22~~~~ air [] destroy
execute as @s if block ~~23~ log2 [] run fill ~~23~~~~ air [] destroy
execute as @s if block ~~24~ log2 [] run fill ~~24~~~~ air [] destroy
execute as @s if block ~~25~ log2 [] run fill ~~25~~~~ air [] destroy
execute as @s if block ~~26~ log2 [] run fill ~~26~~~~ air [] destroy


execute as @s if block ~~1~ log [] run fill ~~1~~~~ air [] destroy
execute as @s if block ~~2~ log [] run fill ~~2~~~~ air [] destroy
execute as @s if block ~~3~ log [] run fill ~~3~~~~ air [] destroy
execute as @s if block ~~4~ log [] run fill ~~4~~~~ air [] destroy
execute as @s if block ~~5~ log [] run fill ~~5~~~~ air [] destroy
execute as @s if block ~~6~ log [] run fill ~~6~~~~ air [] destroy
execute as @s if block ~~7~ log [] run fill ~~7~~~~ air [] destroy
execute as @s if block ~~8~ log [] run fill ~~8~~~~ air [] destroy
execute as @s if block ~~9~ log [] run fill ~~9~~~~ air [] destroy
execute as @s if block ~~10~ log [] run fill ~~10~~~~ air [] destroy
execute as @s if block ~~11~ log [] run fill ~~11~~~~ air [] destroy
execute as @s if block ~~12~ log [] run fill ~~12~~~~ air [] destroy
execute as @s if block ~~13~ log [] run fill ~~13~~~~ air [] destroy
execute as @s if block ~~14~ log [] run fill ~~14~~~~ air [] destroy
execute as @s if block ~~15~ log [] run fill ~~15~~~~ air [] destroy
execute as @s if block ~~16~ log [] run fill ~~16~~~~ air [] destroy
execute as @s if block ~~17~ log [] run fill ~~17~~~~ air [] destroy
execute as @s if block ~~18~ log [] run fill ~~18~~~~ air [] destroy
execute as @s if block ~~19~ log [] run fill ~~19~~~~ air [] destroy
execute as @s if block ~~20~ log [] run fill ~~20~~~~ air [] destroy
execute as @s if block ~~21~ log [] run fill ~~21~~~~ air [] destroy
execute as @s if block ~~22~ log [] run fill ~~22~~~~ air [] destroy
execute as @s if block ~~23~ log [] run fill ~~23~~~~ air [] destroy
execute as @s if block ~~24~ log [] run fill ~~24~~~~ air [] destroy
execute as @s if block ~~25~ log [] run fill ~~25~~~~ air [] destroy
execute as @s if block ~~26~ log [] run fill ~~26~~~~ air [] destroy

execute as @s if block ~~1~ log [] run fill ~~1~~~~ air [] destroy
execute as @s if block ~~2~ log [] run fill ~~2~~~~ air [] destroy
execute as @s if block ~~3~ log [] run fill ~~3~~~~ air [] destroy
execute as @s if block ~~4~ log [] run fill ~~4~~~~ air [] destroy
execute as @s if block ~~5~ log [] run fill ~~5~~~~ air [] destroy
execute as @s if block ~~6~ log [] run fill ~~6~~~~ air [] destroy
execute as @s if block ~~7~ log [] run fill ~~7~~~~ air [] destroy
execute as @s if block ~~8~ log [] run fill ~~8~~~~ air [] destroy
execute as @s if block ~~9~ log [] run fill ~~9~~~~ air [] destroy
execute as @s if block ~~10~ log [] run fill ~~10~~~~ air [] destroy
execute as @s if block ~~11~ log [] run fill ~~11~~~~ air [] destroy
execute as @s if block ~~12~ log [] run fill ~~12~~~~ air [] destroy
execute as @s if block ~~13~ log [] run fill ~~13~~~~ air [] destroy
execute as @s if block ~~14~ log [] run fill ~~14~~~~ air [] destroy
execute as @s if block ~~15~ log [] run fill ~~15~~~~ air [] destroy
execute as @s if block ~~16~ log [] run fill ~~16~~~~ air [] destroy
execute as @s if block ~~17~ log [] run fill ~~17~~~~ air [] destroy
execute as @s if block ~~18~ log [] run fill ~~18~~~~ air [] destroy
execute as @s if block ~~19~ log [] run fill ~~19~~~~ air [] destroy
execute as @s if block ~~20~ log [] run fill ~~20~~~~ air [] destroy
execute as @s if block ~~21~ log [] run fill ~~21~~~~ air [] destroy
execute as @s if block ~~22~ log [] run fill ~~22~~~~ air [] destroy
execute as @s if block ~~23~ log [] run fill ~~23~~~~ air [] destroy
execute as @s if block ~~24~ log [] run fill ~~24~~~~ air [] destroy
execute as @s if block ~~25~ log [] run fill ~~25~~~~ air [] destroy
execute as @s if block ~~26~ log [] run fill ~~26~~~~ air [] destroy