kill @e[type=item,r=2,name="Cobre crudo"]
kill @e[type=item,r=2,name="Raw Copper"]
kill @e[type=item,r=2,name="Cuivre brut"]
kill @e[type=item,r=2,name="Rame grezzo"]
kill @e[type=item,r=2,name="Nyersréz"]
kill @e[type=item,r=2,name="Ruw koper"]
kill @e[type=item,r=2,name="Råkobber"]
kill @e[type=item,r=2,name="Surowa miedź"]
kill @e[type=item,r=2,name="Cobre Bruto"]
kill @e[type=item,r=2,name="Surová meď"]
kill @e[type=item,r=2,name="Raakakupari"]
kill @e[type=item,r=2,name="Ham Bakır"]
kill @e[type=item,r=2,name="Cobre bruto"]
kill @e[type=item,r=2,name="Ruhkupfer"]
kill @e[type=item,r=2,name="Rakobber"]
kill @e[type=item,r=2,name="Tembaga Mentah"]