kill @e[type=item,r=2,name="Oro crudo"]
kill @e[type=item,r=2,name="Raw Gold"]
kill @e[type=item,r=2,name="Or brut"]
kill @e[type=item,r=2,name="Oro grezzo"]
kill @e[type=item,r=2,name="Nyersarany"]
kill @e[type=item,r=2,name="Ruw goud"]
kill @e[type=item,r=2,name="Rågull"]
kill @e[type=item,r=2,name="Surowe złoto"]
kill @e[type=item,r=2,name="Ouro Bruto"]
kill @e[type=item,r=2,name="Surové zlato"]
kill @e[type=item,r=2,name="Raakakulta"]
kill @e[type=item,r=2,name="Ham Altın"]
kill @e[type=item,r=2,name="Oro bruto"]
kill @e[type=item,r=2,name="Rohgold"]
kill @e[type=item,r=2,name="Råguld"]
kill @e[type=item,r=2,name="Emas Mentah"]