kill @e[type=item,r=2,name="Hierro crudo"]
kill @e[type=item,r=2,name="Raw Iron"]
kill @e[type=item,r=2,name="Fer brut"]
kill @e[type=item,r=2,name="Ferro grezzo"]
kill @e[type=item,r=2,name="Nyersvas"]
kill @e[type=item,r=2,name="Ruw ijzer"]
kill @e[type=item,r=2,name="Råjern"]
kill @e[type=item,r=2,name="Surowe żelazo"]
kill @e[type=item,r=2,name="Ferro Bruto"]
kill @e[type=item,r=2,name="Surové železo"]
kill @e[type=item,r=2,name="Raakarauta"]
kill @e[type=item,r=2,name="Råjärn"]
kill @e[type=item,r=2,name="Råguld"]
kill @e[type=item,r=2,name="Råkoppar"]
kill @e[type=item,r=2,name="Ham Demir"]
kill @e[type=item,r=2,name="Hierro bruto"]
kill @e[type=item,r=2,name="Roheisen"]
kill @e[type=item,r=2,name="Besi Mentah"]